### ISSUE TITLE
BGM doesn't work.

### ISSUE THREAD

**Issue by gaurav-src** [NKJ-C4/stalin-game#1]
Clicking on the top left icon to toggle BGM just doesn't work. It stays muted.

This issue breaks the immersion. Can't stay motivated for the motherland.

/s

**Comment by NKJ-C4** [comment]
Fiefox users need to "allow" playing audio first :) Autoplay features are by default denied by the browser.

**Comment by NKJ-C4** [comment]
In addition, the normal HTML attribute "autoplay" seems to be functioning only when followed by a "muted" attribute. And no sense leaving a BGM muted - for the USERS to explicitly PLAY it. So, bear the pain with me comrade ;_;

**Comment by gaurav-src** [comment]
Ok, the hymn works as intended. You are a gem to the Mother Motherland. Thank you for your service.
